---
- name: Deploy k3s on masters
  hosts: masters
  become: true
  roles:
    - k3s-master
    - install-required-packages

- name: Deploy k3s on workers
  hosts: workers
  become: true
  roles:
    - k3s-worker

- name: Add node records to /etc/hosts of each node
  hosts: all
  become: true
  roles:
    - add-etc-hosts

- name: Create deployer service account and secret
  hosts: "{{ groups['masters'] | random }}"
  become: true
  roles:
    - create-user

- name: Copy kube config to all master nodes
  hosts: masters
  become: true
  roles:
    - copy-kubeconfig

- name: Install node exporter
  hosts: all
  become: true
  roles:
    - monitoring/node-exporter

- name: Deploy monitoring on k3s cluster
  hosts: "{{ groups['masters'] | random }}"
  become: true
  roles:
    - monitoring/namespace
    - monitoring/grafana
    - monitoring/prometheus
    - monitoring/alertmanager

- name: Restore Grafana DB
  hosts: "{{ groups['masters'] | random }}"
  roles:
    - monitoring/restore_grafana_db

- name: Deploy postgres cluster
  hosts: "{{ groups['masters'] | random }}"
  roles:
    - postgres-cluster/namespace
    - postgres-cluster/bootstrap

- name: Deploy ip location service
  hosts: "{{ groups['masters'] | random }}"
  roles:
    - deploy-ip-location-service

- name: Cleanup nodes
  hosts: masters
  become: true
  roles:
    - cleanup

