---
- name: Install k3s on master
  shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    executable: /bin/bash
  environment:
    INSTALL_K3S_EXEC: "server --cluster-init --etcd-expose-metrics=true --node-external-ip {{ ansible_ssh_host }}"

- name: Get the node token
  command: cat /var/lib/rancher/k3s/server/node-token
  register: node_token
  changed_when: false

- name: Save node token for workers
  set_fact:
    k3s_token: "{{ node_token.stdout }}"
