name: Build

on:
  push:
    branches: [ "*" ]
    # branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
    # branches: [ "master" ]

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push the image
      working-directory: ip-locations
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
        IMAGE=mhbahmani/ip-location:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE
        docker push $IMAGE
