name: Build

on:
  push:
    branches: [ "*" ]
    # branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
    # branches: [ "master" ]

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  IMAGE: mhbahmani/ip-location:$(date +%s)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: change directory
      run: cd ip-location;
    - name: login
      run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS;
    - name: build the image
      run: docker build . --file Dockerfile --tag $IMAGE;
    - name: push the image to docker hub
      run: docker push $IMAGE; 
